# Generated by Django 3.1.5 on 2021-05-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('roll_no', models.IntegerField()),
                ('markp', models.IntegerField()),
                ('markm', models.IntegerField()),
                ('markc', models.IntegerField()),
                ('total', models.IntegerField()),
                ('percentage', models.IntegerField()),
            ],
        ),
    ]
