# Generated by Django 3.1.5 on 2021-05-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0002_auto_20210518_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='Percentage',
            field=models.FloatField(),
        ),
    ]
